# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
# repositories:
#   stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    xentaurs_config_management_workshop_puppet/files: '../../../../files'
    xentaurs_config_management_workshop_puppet/manifests: '../../../../manifests'
    xentaurs_config_management_workshop_puppet/templates: '../../../../templates'
